# Generated by Django 3.1.5 on 2021-03-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.AddField(
            model_name='alumno',
            name='Apellido1',
            field=models.TextField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Apellido2',
            field=models.TextField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Email',
            field=models.EmailField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Escolaridad',
            field=models.TextField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Nombre',
            field=models.TextField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=0, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Matricula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
