# Generated by Django 3.1.5 on 2021-03-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210303_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='Id_Alumno',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Apellido1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Apellido2',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Escolaridad',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Matricula',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='created',
            field=models.DateTimeField(verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='updated',
            field=models.DateTimeField(verbose_name='Fecha de Edición'),
        ),
    ]
