# Generated by Django 3.1.5 on 2021-03-08 05:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210307_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 8, 5, 18, 33, 439576, tzinfo=utc), verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición'),
        ),
    ]
