# Generated by Django 3.1.5 on 2021-04-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210307_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alumno',
        ),
    ]
