# Generated by Django 3.1.5 on 2021-03-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PeriodoAct', models.IntegerField()),
                ('Grupo', models.CharField(max_length=1)),
                ('Beca', models.IntegerField()),
                ('FechaInicio', models.DateField()),
                ('FechaFinal', models.DateField()),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.alumno')),
                ('Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.carrera')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Registro Academico',
            },
        ),
    ]
