# Generated by Django 3.1.5 on 2021-03-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0002_historial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'verbose_name': 'Regristo Academico', 'verbose_name_plural': 'Historial'},
        ),
    ]
