# Generated by Django 3.1.5 on 2021-03-22 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0003_auto_20210322_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Colegiatura', models.BooleanField()),
                ('CantidadPagada', models.IntegerField()),
                ('PagosExtra', models.IntegerField()),
                ('Historial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.historial')),
            ],
            options={
                'verbose_name': 'HistorialPago',
                'verbose_name_plural': 'HistorialPagos',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Motivo', models.CharField(max_length=500)),
                ('CostoPagar', models.IntegerField()),
                ('HistorialPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.historialpago')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
    ]
