# Generated by Django 3.1.5 on 2021-04-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0004_historialpago_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
