# Generated by Django 3.1.5 on 2021-04-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0005_auto_20210409_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='Beca',
        ),
        migrations.AlterField(
            model_name='carrera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
