# Generated by Django 3.1.5 on 2021-04-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDatos', '0006_auto_20210419_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('MontoTotal', models.IntegerField(default=0)),
                ('Abono', models.IntegerField(default=0)),
                ('Resto', models.IntegerField(default=0)),
                ('FechaPago', models.DateField()),
                ('FechaLimite', models.DateField()),
                ('Beca', models.CharField(default=0, max_length=50)),
                ('Cargo', models.IntegerField(default=0)),
                ('liquidado', models.BooleanField(default=False)),
                ('Historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatos.alumno')),
            ],
            options={
                'verbose_name': 'Pagos',
                'verbose_name_plural': 'Historial de Pagos',
            },
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='HistorialPago',
        ),
        migrations.DeleteModel(
            name='HistorialPago',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
